# Настройки linux-punto-switcher

# сочетания клавиш могут состоять из нуля или более модификаторов и основной клавиши. Это всё разделяется знаком +, пробелы недопустимы, регистр не имеет значения
# например
#      PAUSE
#      Ctrl+Minus
#      shift+equal
#      ALT+META+C

# модификаторы: CTRL SHIFT ALT META WIN (META и WIN - одно и то же)

# основные клавиши (то что в скобках - только подсказки, их не надо указывать):
# 1 2 3 4 5 6 7 8 9 0 Q W E R T Y U I O P A S D F G H J K L Z X C V B N M 
# MINUS(-) EQUAL(=) LEFTBRACE([) RIGHTBRACE(]) SEMICOLON(;) APOSTROPHE(') GRAVE(`) BACKSLASH(\) COMMA(,) DOT(.) SLASH(/) SPACE( )
# (numpad клавиатура:) KPASTERISK NUMLOCK KPMINUS KPPLUS KP0 KP1 KP2 KP3 KP4 KP5 KP6 KP7 KP8 KP9 KPDOT KPENTER KPSLASH
# ESC BACKSPACE TAB ENTER CAPSLOCK LINEFEED HOME END PAGEUP PAGEDOWN INSERT DELETE UP LEFT RIGHT DOWN SYSRQ(PrtScr) SCROLLLOCK PAUSE(Break) COMPOSE(context menu)
# F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12

# основные клавиши, которые скорее всего отсутствуют на вашей клавиатуре:
# KPEQUAL KPPLUSMINUS KPCOMMA KPJPCOMMA KPLEFTPAREN KPRIGHTPAREN 
# F13 F14 F15 F16 F17 F18 F19 F20 F21 F22 F23 F24 
# ZENKAKUHANKAKU RO KATAKANA HIRAGANA HENKAN KATAKANAHIRAGANA MUHENKAN HANGEUL HANJA YEN
# MACRO MUTE VOLUMEDOWN VOLUMEUP POWER SCALE STOP AGAIN PROPS UNDO FRONT COPY OPEN PASTE
# FIND CUT HELP MENU CALC SETUP SLEEP WAKEUP FILE SENDFILE DELETEFILE XFER PROG1 PROG2 WWW MSDOS COFFEE ROTATE_DISPLAY
# CYCLEWINDOWS MAIL BOOKMARKS COMPUTER BACK FORWARD CLOSECD EJECTCD EJECTCLOSECD NEXTSONG PLAYPAUSE PREVIOUSSONG STOPCD RECORD REWIND
# PHONE ISO CONFIG HOMEPAGE REFRESH EXIT MOVE EDIT SCROLLUP SCROLLDOWN NEW REDO PLAYCD PAUSECD PROG3 PROG4 ALL_APPLICATIONS SUSPEND CLOSE
# PLAY FASTFORWARD BASSBOOST PRINT HP CAMERA SOUND QUESTION EMAIL CHAT SEARCH CONNECT FINANCE SPORT SHOP ALTERASE CANCEL
# BRIGHTNESSDOWN BRIGHTNESSUP MEDIA SWITCHVIDEOMODE KBDILLUMTOGGLE KBDILLUMDOWN KBDILLUMUP SEND REPLY FORWARDMAIL SAVE DOCUMENTS BATTERY
# BLUETOOTH WLAN UWB UNKNOWN VIDEO_NEXT VIDEO_PREV BRIGHTNESS_CYCLE BRIGHTNESS_AUTO DISPLAY_OFF WWAN RFKILL MICMUTE


# как настроена смена раскладки в вашей системе?
# здесь также можно использовать сочетания без основной клавиши, например CTRL+SHIFT
change-layout : CAPSLOCK

# при нажатии на эту клавишу будет изменяться раскладка последнего набранного слова
fix-last-word : PAUSE

# при нажатии на эту клавишу будет изменяться раскладка выделенного текста
fix-selected : ALT+PAUSE

# при нажатии на эту клавишу будет изменяться регистр выделенного текста
swapcase-selected : SHIFT+PAUSE

